version: "3"

services:
  vpnserver:
    image: vpnserver
    hostname: vpnserver
    container_name: vpnserver
    restart: always
    network_mode: "bridge"
    ports:
      - "443:443/tcp"
    volumes:
      - ./vpn_server.config:/etc/vpnserver/vpn_server.config
    build:
      context: .