version: "3"

services:
  SoftEtherVPN:
    image: SoftEtherVPN
    hostname: SoftEtherVPN
    container_name: SoftEtherVPN
    restart: always
    network_mode: "bridge"
    ports:
      - "443:443/tcp"
    volumes:
      - ./vpn_server.config:/etc/vpnserver/vpn_server.config
    build:
      context: .